#!/bin/bash

function backup {
    cp -R $1 backup-dir
}

mkdir backup-dir
backup "app"
backup "cordova-merge"
backup "documents"
backup "raw-assets"
backup "statics"
backup ".gitignore"
backup ".jshintrc"
backup "build-audio.js"
backup "convert-tiffs.js"
backup "cordova-utility.js"
backup "current-edits.docx"
backup "gulpfile.js"
backup "package.json"
backup "backup"

tar -zcvf "fun-time-phonics.tar.gz" ./backup-dir &&
sshpass -p "ctADl0g1n" scp fun-time-phonics.tar.gz james@12.0.0.70:/home/james/server/backups/ &&
rm -rf backup-dir &&
rm fun-time-phonics.tar.gz