/* This file is automatically generated by gulpfile.js task "index-lessons" */

module.exports = {
    "1": require("screens/lessons/1/lesson-feedback"),
    "10": require("screens/lessons/10/lesson-feedback"),
    "11": require("screens/lessons/11/lesson-feedback"),
    "12": require("screens/lessons/12/lesson-feedback"),
    "13": require("screens/lessons/13/lesson-feedback"),
    "14": require("screens/lessons/14/lesson-feedback"),
    "15": require("screens/lessons/15/lesson-feedback"),
    "16": require("screens/lessons/16/lesson-feedback"),
    "17": require("screens/lessons/17/lesson-feedback"),
    "2": require("screens/lessons/2/lesson-feedback"),
    "3": require("screens/lessons/3/lesson-feedback"),
    "4": require("screens/lessons/4/lesson-feedback"),
    "5": require("screens/lessons/5/lesson-feedback"),
    "6": require("screens/lessons/6/lesson-feedback"),
    "7": require("screens/lessons/7/lesson-feedback"),
    "8": require("screens/lessons/8/lesson-feedback"),
    "9": require("screens/lessons/9/lesson-feedback")
};