/* This file is automatically generated by gulpfile.js task "index-lessons" */

module.exports = {
    "1": require("screens/lessons/1"),
    "1-g": require("screens/lessons/1-g"),
    "1-l": require("screens/lessons/1-l"),
    "1-m": require("screens/lessons/1-m"),
    "1-n": require("screens/lessons/1-n"),
    "1-r": require("screens/lessons/1-r"),
    "1-s": require("screens/lessons/1-s"),
    "10": require("screens/lessons/10"),
    "2": require("screens/lessons/2"),
    "2-b": require("screens/lessons/2-b"),
    "2-d": require("screens/lessons/2-d"),
    "2-f": require("screens/lessons/2-f"),
    "2-k": require("screens/lessons/2-k"),
    "2-m": require("screens/lessons/2-m"),
    "2-p": require("screens/lessons/2-p"),
    "3": require("screens/lessons/3"),
    "4": require("screens/lessons/4"),
    "5": require("screens/lessons/5"),
    "6": require("screens/lessons/6"),
    "7": require("screens/lessons/7"),
    "8": require("screens/lessons/8"),
    "9": require("screens/lessons/9")
};